// components/ProjectHighlight.vue
<template>
  <div style="margin: 0">
    <b-container fluid>
      <b-row no-gutters>
        <b-col :order-md="setOrder" md>
          <b-container>
            <div class="project-summary mx-auto">
              <h2>{{ title }}</h2>
              <p>{{ summary }}</p>

              <div class="tag-holder">
                <b-badge
                v-for="tag in projectTags"
                :key="tag.tags"
                variant="dark"
                >
                  {{ tag }}
                </b-badge>
              </div>

              <b-button v-if="projectLink"
              :href="projectLink"
              variant="outline-info"
              target="_blank"
              class="project-explore-button"
              size="md">
                Explore
              </b-button>
              <b-button v-if="caseStudyLink"
              :to="caseStudyLink"
              variant="outline-info"
              class=""
              size="md">
                Case study
              </b-button>
            </div>
          </b-container>
        </b-col>
        <b-col order-md="1" md>
          <div class="grow-img container">
            <nuxt-link :to="caseStudyLink">
              <transition name="fade">
                <b-img class="image"
                :src="image"
                fluid
                alt="Responsive image"
                v-on:load="onLoaded"
                v-show="loaded"></b-img>
              </transition>
            </nuxt-link>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
export default {
  name: 'ProjectHighlight',
  props: {
    title: {
      type: String,
      default: null
    },
    summary: {
      type: String,
      default: null
    },
    image: {
      type: String,
      default: null
    },
    imageside: {
      type: String,
      default: "left"
    },
    caseStudy: {
      type: String,
      default: null,
      required: false
    },
    projectTags: {
      type: Array,
      required: false
    },
    caseStudyLink: {
      type: String,
      requred: false
    },
    projectLink: {
      type: String,
      requred: false
    }
  },
  data: function() {
    return {
      loaded: false
    }
  },
  computed: {
    setOrder() {
      if (this.imageside === "left") {
        return "1"
      } else {
        return "2"
      }
    }
  },
  methods: {
    onLoaded() {
      this.loaded = true;
    }
  }
}
</script>

<style lang="css">
  .project-summary {
    max-width: 450px;
    margin-top: 20%;
    margin-left: 10px;
    margin-right: 5px;
    padding: 14px
  }

  .project-summary h2 {
    font-size: 3.5vmax
  }

  .project-summary p {
    font-size: 21px;
    margin-top: 10px
  }

.image {
  opacity: 1;
  display: block;
  width: 100%;
  height: auto;
  transition: .5s ease;
  backface-visibility: hidden;
}

.container {
  position: relative;
  margin: 0;
  padding: 0
}

.container:hover .image {
  opacity: 0.5;
}

.container:hover .middle {
  opacity: 1;
}

.tag-holder {
  margin-bottom: 20px;
  margin-top: 20px;
}

.badge {
  padding: 5px;
  margin-right: 10px
}

.fade-enter-active {
  transition: opacity 1s ease-in-out;
}

.fade-enter-to {
  opacity: 1;
}

.fade-enter {
  opacity: 0;
}

.project-explore-button {
  margin-right: 10px
}
</style>

// src/components/ProjectHighlight.svelte
<script>
    export let image;
    export let title;
    export let description;
    export let link;
	export let imgAlt;
	export let tags = "";
    export let imgSide = "right";

	let width, imageSideAfterWidthCheck;

	if (tags != "") {
		tags = tags.split(',')
	}

	$: if (width < 800) {
		imageSideAfterWidthCheck = "right"
	} else {
		imageSideAfterWidthCheck = imgSide
	}
</script>

<svelte:window bind:innerWidth={width}/>

<main>
    <div class="row project-row">
        {#if imageSideAfterWidthCheck == "right"}
		<div class="column _30">
			<div class="project-text">
				<h2>{title}</h2>
                <p>{description}</p>
				<div class="tag-container">
                    {#each tags as tag}
                    <span>{tag}</span>
                    {/each}
                </div>
			</div>
		</div>
		<div class="column _50">
			<div class="img-holder">
				<a href={link} target="_blank">
			    	<img src={image} alt={imgAlt}>
					<div class="img-overlay"></div>
				</a>
		    </div>
        </div>
        {:else}
        <div class="column _50">
			<div class="img-holder">
				<a href={link} target="_blank">
			    	<img src={image} alt={imgAlt}>
					<div class="img-overlay"></div>
				</a>
            </div>
		</div>
		<div class="column _30">
            <div class="project-text">
				<h2>{title}</h2>
                <p>{description}</p>
				<div class="tag-container">
                    {#each tags as tag}
                    <span>{tag}</span>
                    {/each}
                </div>
			</div>
        </div>
        {/if}
	</div>
</main>

<style>
    .project-row {
		background-color:#191b1d;
		height: 50vh;
	}

	.tag-container {
		margin-top: 0px
	}

	span {
        border-radius: 8px;
        background-color:rgb(194, 194, 194);
		color: black;
        padding-left: 12px;
        padding-right: 12px;
        padding-top: 4px;
        padding-bottom: 4px;
        margin: 4px;
        font-size: 14px;
    }

	.img-holder {
		position: relative;
	}

	.img-overlay {
		position: absolute;
		width: 100%;
		height: 100%;
		top: 0;
		left: 0;
		background-color:#1C1F23;
		opacity: 0.4;
		transition: 1s;
	}

	.img-overlay:hover {
		transition: 1s;
		opacity: 0;
	}

	.img-holder img {
        object-fit: cover;
        object-position: 20% 30%;
        width: 100%;
        height: 50vh;
	}
	
	.project-text {
		padding: 10px;
		max-width: 400px;
		margin: 0 auto;
		margin-top: 10px;
		margin-bottom: 0px
	}

	h2 {
		font-size: 36px
	}

	p {
		font-size: 21px;
		line-height: 1.6
	}

	@media screen and (max-width: 800px) {
		.column {
			/* height: 500px; */
			display: block
		}

		.project-row {
			height: 100%
		}

		h2 {
			font-size: 26px
		}

		.tag-container {
			margin-bottom: 15px
		}
	}

</style>
